### PR TITLE
Permit submission of compressed packets and rectification of missing default strings

### PR DESCRIPTION
**Pull request by chucklin85**
APRS over HF it is considered a bad idea to submit packets that are not compressed either in APRS Compressed or Mic-E formats. This patch uses a customised version of javAPRSlib (pull request is open with ab0oo for the required change in that library) which enables aprsdroid to set compressed packets for positions.

This adds an additional configuration item under the Location preferences to enable compressed packets and changes the behaviour in the AprsService class when submitting positions.

Further enhancements are to be completed to compress the speed and altitude. This is a work in progress for that additional functionality over the next week or so.

### CODE REVIEW

**Comment by ge0rg** [comment]
I like your idea, and I'm eager to merge the patches. Could you please do some minor cleanups first, though?

1. You are doing some unneeded copy&pasting in res/values/strings.xml
2. Please add the new "Compressed Position" checkbox at the top of res/xml/location.xml to unclutter the already-long main preferences screen, with the strings in res/values/strings.xml
3. Speed, bearing and altitude can be disabled in Location Privacy settings, they shouldn't be affected by the compression flag.

**Comment by chucklin85** [comment]
No problem. I will fix up items 1 and 2.

With 3, I will implement the compression of altitude, speed and bearing etc. I had dosabled these as those strings are handled in aprsdroid itself and simply append to the end of the position data. The problem is those values are actually in the wrong format for compressed APRS. I will try and implement these shortly so it is full functionality.

**Comment by ge0rg** [comment]
Ah, right. Compressed packet format is borderline-insane. I'd suggest adding a new method `AprsPacket.formatCourseSpeedCompressed`, and replacing the last three characters of `pos.toCompressedString()` with it, unless privacy is enabled.

It looks like the compressed format can not hold both altitude and CS, so I'd suppose we need to keep the ASCII /A= field.

**Comment by chucklin85** [comment]
I think I am all done now, I've done a few more changes and have squashed these down.

**Comment by chucklin85** [comment]
Latest update to include capability to parse weather data packets and present them in a format that can be read by users after completing unit conversion and string formatting. This is displayed above the comment in another textview.

**Comment by chucklin85** [comment]
Closing pull request as I've got a couple of other features (incl Dual TNC support) and other packet type parsing I'd like to finish and send in "en-bloc".

**Comment by sh123** [comment]
@ge0rg , @mpannen1979, this pull request is dropped? Any plans to continue with compressed packet support?

**Pull request closed without merging**
