### PR TITLE
Update StationListAdapter.scala for WX Parsing

### PR DESCRIPTION
**Pull request by ioef**
Added a method that distinguishes WX Messages from other Messages. Then via another method we parse the contents and print them in human readable format.

### CODE REVIEW

**Comment by na7q** [comment]
Can't wait to check this out! Thanks!

**Comment by na7q** [comment]
This is missing the station_report in the layout. There are other issues.
Don't have time to investigate it entirely. I will look at it more this evening.

Good start though! I will definitely add this to my builds.

**Comment by ioef** [comment]
I am closing it since i have managed to compile the project and actually working upon the WX issue.  In the meantime the compilation have been achieved via Dockerfiles based on the approach you already suggested. I will reattempt a pull request at a later point with a squashed commit.

**Comment by na7q** [comment]
That sounds great. I haven't had time to work on this more. But knowing you're doing some of that is great. I just implemented Mic-E beacons last night, and working on some more big things today. Thanks for working on this!

**Pull request closed without merging**
